In [1]:
import pandas as pd

In [2]:
df = pd.read_json('data.json')

In [3]:
df

   Gender  HeightCm  WeightKg
0    Male       171        96
1    Male       161        85
2    Male       180        77
3  Female       166        62
4  Female       150        70
5  Female       167        82

### Calculating BMI, BMI Category, BMI Range (kg/m2), Health risk

In [4]:
def BMI(df):
    try:
        assert df['WeightKg'] > 0 and df['HeightCm'] > 0
        # checking for correct data. Weight and Height cannot be less than or equal to zero
    except:
        return None
    try:
        x = df['WeightKg']/(df['HeightCm']/100)
    except ZeroDivisionError:
        return None
    
    return x

def BMI_Category(df):
    if df['BMI'] <= 18.4:
        return "Underweight"
    elif df['BMI'] >= 18.5 and df['BMI'] <= 24.9:
        return "Normal weight"
    elif df['BMI'] >= 25 and df['BMI'] <= 29.9:
        return "Over weight"
    elif df['BMI'] >= 30 and df['BMI'] <= 34.9:
        return "Moderately obese"
    elif df['BMI'] >= 35 and df['BMI'] <= 39.9:
        return "Severely obese"
    elif df['BMI'] >= 40:
        return "Very severely obese"
    else:
        return None

def Health_Risk(df):
    if df['BMI'] <= 18.4:
        return "Malnutrition risk"
    elif df['BMI'] >= 18.5 and df['BMI'] <= 24.9:
        return "Low risk"
    elif df['BMI'] >= 25 and df['BMI'] <= 29.9:
        return "Enhanced risk"
    elif df['BMI'] >= 30 and df['BMI'] <= 34.9:
        return "Medium risk"
    elif df['BMI'] >= 35 and df['BMI'] <= 39.9:
        return "High risk"
    elif df['BMI'] >= 40:
        return "Very High risk"
    else:
        return None
    
def BMI_Range(df):
    if df['BMI'] <= 18.4:
        return "18.4 and Below"
    elif df['BMI'] >= 18.5 and df['BMI'] <= 24.9:
        return "18.5 - 24.9"
    elif df['BMI'] >= 25 and df['BMI'] <= 29.9:
        return "25 - 29.9"
    elif df['BMI'] >= 30 and df['BMI'] <= 34.9:
        return "30 - 34.9"
    elif df['BMI'] >= 35 and df['BMI'] <= 39.9:
        return "35 - 39.9"
    elif df['BMI'] >= 40:
        return "40 and above"
    else:
        return None
    
df = df.assign(BMI = df.apply(BMI, axis=1)) 
df = df.assign(BMI_Category = df.apply(BMI_Category, axis=1))
df = df.assign(BMI_Range_kg_m2 = df.apply(BMI_Range, axis=1))
df = df.assign(Health_Risk = df.apply(Health_Risk, axis=1)) 
df

,Gender,HeightCm,WeightKg,BMI,BMI_Category,BMI_Range_kg_m2,Health_Risk
0,Male,171,96,56.140351,Very severely obese,40 and above,Very High risk
1,Male,161,85,52.795031,Very severely obese,40 and above,Very High risk
2,Male,180,77,42.777778,Very severely obese,40 and above,Very High risk
3,Female,166,62,37.349398,Severely obese,35 - 39.9,High risk
4,Female,150,70,46.666667,Very severely obese,40 and above,Very High risk
5,Female,167,82,49.101796,Very severely obese,40 and above,Very High risk

### Total number of overweight people

In [5]:
df[~df['BMI_Category'].isin(['Normal weight',['Underweight']])]['Gender'].count()

6